// Works only in VScode using Rest Client

// Test: Get all posts
GET http://localhost:3000/api/posts/

#########

// Test: Add post
POST http://localhost:3000/api/posts/ 
Content-Type: application/json

{
    "title":"First post",
    "content":"React/Redux",
    "email":"test@email.com",
    "username": "Jack Sparrow"
}

##########

// Test: Edit post
PUT http://localhost:3000/api/posts/58
Content-Type: application/json

{
    "title": " Updated title 331111",
    "content": "updated content111111",
    "id": 58
}

#######

// Test: Delete post
DELETE http://localhost:3000/api/posts/31
Content-Type: application/json



##################

// CREATE USER 
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "username": "test",
    "password": "password1",
    "email": "test@email.com",
    "role": "user",
    "likes": 0,
    "coments": 0
}

##################

// Authenticate (Test)
POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "username": "yshchelkunov",
    "password": "password"
}